receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      load:
      memory:
      network:

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024
  resource:
    attributes:
      - key: deployment.environment
        value: local
        action: upsert
      - key: service.namespace
        value: engineer-cafe-navigator
        action: upsert

exporters:
  prometheus:
    endpoint: 0.0.0.0:9464
    send_timestamps: true
    metric_expiration: 10m
    enable_open_metrics: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
  debug:
    verbosity: basic
  googlecloud:
    user_agent: engineer-cafe-navigator-otel

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [resource, batch]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp/loki, debug]
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug]
