export const overlayLabels = {
  ja: {
    guideLabel: '音声ガイド',
    responseLabel: '応答',
    transcriptLabel: '聞き取り結果',
    loadingLabel: '応答を準備しています',
    wakeWordReady: 'ウェイクワード待機中',
    wakeWordOff: 'マイクボタンで開始',
    idleAction: '話しかける',
    listeningAction: '録音を止める',
    processingAction: '処理中',
    speakingAction: '応答を再生中',
    defaultPrompt: 'マイクを押して、エンジニアカフェについて聞いてください。',
    helperPrompt: '音声が中心です。必要なときだけテキスト入力を開けます。',
    switchTextInput: '文字入力',
    switchVoiceInput: '音声入力',
    textPlaceholder: 'ここに質問を入力します',
    send: '送信',
    openSlides: 'スライド案内',
    closeSlides: 'スライドを閉じる',
    clearConversation: '会話をクリア',
    cancelSession: '応答を止める',
    languageJa: '日本語',
    languageEn: 'English',
    currentLocale: '現在: 日本語',
    kioskWelcome: 'Welcome',
    kioskVoice: '音声応対',
    kioskVoicePushIdle: '押して話す',
    kioskVoicePushActive: '離すと送信',
    kioskVoiceToggleActive: '録音中',
    kioskOcrMember: '会員証',
    kioskOcrHandwriting: '筆談',
    kioskSlides: 'スライド案内',
    kioskBackIdle: 'メニューに戻る',
    ocrModeMember: '会員証',
    ocrModeHandwriting: '筆談',
    sttReading: '音声読み取り中...',
    listeningNow: '聞き取り中です。話しかけてください。',
    preparingAnswer: '応答を準備しています...',
    ttsSynthesizing: '音声合成中...',
    ocrMemberResult: '会員証読み取り結果',
    ocrHandwritingResult: '筆談読み取り結果',
    ocrReadFailed: '読み取りに失敗しました。再度お試しください。',
  },
  en: {
    guideLabel: 'Voice Guide',
    responseLabel: 'Answer',
    transcriptLabel: 'Transcript',
    loadingLabel: 'Preparing an answer',
    wakeWordReady: 'Wake word is armed',
    wakeWordOff: 'Use the mic button to start',
    idleAction: 'Start talking',
    listeningAction: 'Stop recording',
    processingAction: 'Processing',
    speakingAction: 'Speaking',
    defaultPrompt: 'Tap the mic and ask anything about Engineer Cafe.',
    helperPrompt: 'Voice comes first. Open text input only when you need a backup.',
    switchTextInput: 'Text input',
    switchVoiceInput: 'Voice input',
    textPlaceholder: 'Type your question here',
    send: 'Send',
    openSlides: 'Open slides',
    closeSlides: 'Close slides',
    clearConversation: 'Clear conversation',
    cancelSession: 'Cancel current turn',
    languageJa: '日本語',
    languageEn: 'English',
    currentLocale: 'Current: English',
    kioskWelcome: 'Welcome',
    kioskVoice: 'Voice chat',
    kioskVoicePushIdle: 'Hold to talk',
    kioskVoicePushActive: 'Release to send',
    kioskVoiceToggleActive: 'Recording',
    kioskOcrMember: 'Member card',
    kioskOcrHandwriting: 'Handwriting',
    kioskSlides: 'Slide guide',
    kioskBackIdle: 'Back to menu',
    ocrModeMember: 'Member card',
    ocrModeHandwriting: 'Handwriting',
    sttReading: 'Transcribing voice...',
    listeningNow: 'Listening. Please speak now.',
    preparingAnswer: 'Preparing an answer...',
    ttsSynthesizing: 'Synthesizing voice...',
    ocrMemberResult: 'Member card result',
    ocrHandwritingResult: 'Handwriting result',
    ocrReadFailed: 'OCR failed. Please try again.',
  },
} as const;

export const kioskSettingsLabels = {
  ja: {
    displayLangTitle: '表示言語',
    displayLangJa: '日本語',
    displayLangEn: 'English',
    triggerTitle: '操作のしかた',
    triggerScreen: '画面の仮想ボタンで操作する',
    triggerDevice: '物理ボタン・センサーで操作する（準備中）',
    micModeTitle: '音声応対のマイクボタン',
    micToggle: '押すたびにON/OFFを切り替える（トグル）',
    micPushToTalk: '押している間だけ聞き取る（プッシュトーク）',
    speakerVolumeTitle: '再生音量',
    microphoneDeviceTitle: '使用するマイク',
    cameraDeviceTitle: '使用するカメラ',
    lightingTitle: 'ライティング設定',
    lightingIntensityLabel: 'ライティング強度',
    lightingPresetDim: '暗い',
    lightingPresetNormal: '標準',
    lightingPresetBright: '明るい',
    lightingPresetStudio: 'スタジオ',
    lightingCurrentSettingsTitle: '現在の設定',
    lightingIntensityValueLabel: '強度',
    lightingToneSoft: 'ソフト',
    lightingToneBalanced: 'バランス',
    lightingToneIntense: '強め',
  },
  en: {
    displayLangTitle: 'Display language',
    displayLangJa: '日本語',
    displayLangEn: 'English',
    triggerTitle: 'How to operate',
    triggerScreen: 'Use virtual buttons on the screen',
    triggerDevice: 'Use physical buttons / sensors (coming soon)',
    micModeTitle: 'Mic button (voice mode)',
    micToggle: 'Tap to toggle ON/OFF',
    micPushToTalk: 'Push and hold to talk (push-to-talk)',
    speakerVolumeTitle: 'Playback volume',
    microphoneDeviceTitle: 'Microphone',
    cameraDeviceTitle: 'Camera',
    lightingTitle: 'Lighting settings',
    lightingIntensityLabel: 'Lighting intensity',
    lightingPresetDim: 'Dim',
    lightingPresetNormal: 'Normal',
    lightingPresetBright: 'Bright',
    lightingPresetStudio: 'Studio',
    lightingCurrentSettingsTitle: 'Current settings',
    lightingIntensityValueLabel: 'Intensity',
    lightingToneSoft: 'Soft',
    lightingToneBalanced: 'Balanced',
    lightingToneIntense: 'Intense',
  },
} as const;

export const initialSettingsModalLabels = {
  ja: {
    title: '初期設定',
    close: '閉じてはじめる',
    noticeFooter: '閉じる操作で音声再生が有効になります。',
  },
  en: {
    title: 'Before you start',
    close: 'Close and continue',
    noticeFooter: 'Closing enables audio playback in the browser.',
  },
} as const;
